# Generated by Django 5.2.3 on 2025-07-18 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default=datetime.date(2025, 8, 1)),
        ),
    ]
