# Generated by Django 5.2.3 on 2025-07-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("income", "Income")],
                default="expense",
                max_length=50,
                verbose_name="Transaction Type",
            ),
        ),
    ]
